using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_StageInfo : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_StageInfo(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_StageInfo(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5498416854868917599UL,3584518102652657800UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String satgeNum
	{
		get => _satgeNum[Index];
		set => _satgeNum[Index] = value;
	}
	public System.Int32 enemyNum
	{
		get => _enemyNum[Index];
		set => _enemyNum[Index] = value;
	}
	public System.String difficulty
	{
		get => _difficulty[Index];
		set => _difficulty[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5759055557064028504UL, 10288621904305714833UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_satgeNum;
	public static BansheeGz.BGDatabase.BGFieldString _satgeNum => _ufle12jhs77_satgeNum ?? (_ufle12jhs77_satgeNum = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4870820815582943281UL, 14185232666207034499UL), () => _ufle12jhs77_satgeNum = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_enemyNum;
	public static BansheeGz.BGDatabase.BGFieldInt _enemyNum => _ufle12jhs77_enemyNum ?? (_ufle12jhs77_enemyNum = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5347023749621567006UL, 9577464003353037992UL), () => _ufle12jhs77_enemyNum = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_difficulty;
	public static BansheeGz.BGDatabase.BGFieldString _difficulty => _ufle12jhs77_difficulty ?? (_ufle12jhs77_difficulty = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4920243121743538009UL, 1048085433160290216UL), () => _ufle12jhs77_difficulty = null));
	private static readonly DB_StageInfo.Factory _factory0_PFS = new DB_StageInfo.Factory();
	private static readonly DB_petsSkill.Factory _factory1_PFS = new DB_petsSkill.Factory();
	private static readonly DB_enemySkill.Factory _factory2_PFS = new DB_enemySkill.Factory();
	private static readonly DB_petInfo.Factory _factory3_PFS = new DB_petInfo.Factory();
	private static readonly DB_enemyInfo.Factory _factory4_PFS = new DB_enemyInfo.Factory();
	private DB_StageInfo() : base(MetaDefault) {}
	private DB_StageInfo(BGId id) : base(MetaDefault, id) {}
	private DB_StageInfo(BGMetaEntity meta) : base(meta) {}
	private DB_StageInfo(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_StageInfo FindEntity(Predicate<DB_StageInfo> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_StageInfo> FindEntities(Predicate<DB_StageInfo> filter, List<DB_StageInfo> result=null, Comparison<DB_StageInfo> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_StageInfo> action, Predicate<DB_StageInfo> filter=null, Comparison<DB_StageInfo> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_StageInfo GetEntity(BGId entityId) => (DB_StageInfo) MetaDefault.GetEntity(entityId);
	public static DB_StageInfo GetEntity(int index) => (DB_StageInfo) MetaDefault[index];
	public static DB_StageInfo GetEntity(string entityName) => (DB_StageInfo) MetaDefault.GetEntity(entityName);
	public static DB_StageInfo NewEntity() => (DB_StageInfo) MetaDefault.NewEntity();
	public static DB_StageInfo NewEntity(BGId entityId) => (DB_StageInfo) MetaDefault.NewEntity(entityId);
	public static DB_StageInfo NewEntity(Action<DB_StageInfo> callback) => (DB_StageInfo) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_StageInfo)entity)));
}

public partial class DB_petsSkill : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_petsSkill(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_petsSkill(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4725162426964347011UL,7944346174665875850UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String skillName
	{
		get => _skillName[Index];
		set => _skillName[Index] = value;
	}
	public System.Int32 lowDamage
	{
		get => _lowDamage[Index];
		set => _lowDamage[Index] = value;
	}
	public System.Int32 highDamage
	{
		get => _highDamage[Index];
		set => _highDamage[Index] = value;
	}
	public System.Int32 useMp
	{
		get => _useMp[Index];
		set => _useMp[Index] = value;
	}
	public System.String skillContent
	{
		get => _skillContent[Index];
		set => _skillContent[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5664165088027681939UL, 12994688545427843258UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillName;
	public static BansheeGz.BGDatabase.BGFieldString _skillName => _ufle12jhs77_skillName ?? (_ufle12jhs77_skillName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5679671725705776143UL, 1516517330677680773UL), () => _ufle12jhs77_skillName = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_lowDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _lowDamage => _ufle12jhs77_lowDamage ?? (_ufle12jhs77_lowDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4667116086976227231UL, 12226225226750604686UL), () => _ufle12jhs77_lowDamage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_highDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _highDamage => _ufle12jhs77_highDamage ?? (_ufle12jhs77_highDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5207148116815162877UL, 16783685417789504696UL), () => _ufle12jhs77_highDamage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_useMp;
	public static BansheeGz.BGDatabase.BGFieldInt _useMp => _ufle12jhs77_useMp ?? (_ufle12jhs77_useMp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4744160979433584149UL, 149813366810198429UL), () => _ufle12jhs77_useMp = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillContent;
	public static BansheeGz.BGDatabase.BGFieldString _skillContent => _ufle12jhs77_skillContent ?? (_ufle12jhs77_skillContent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4860535205846477015UL, 17895207831199564697UL), () => _ufle12jhs77_skillContent = null));
	private static readonly DB_StageInfo.Factory _factory0_PFS = new DB_StageInfo.Factory();
	private static readonly DB_petsSkill.Factory _factory1_PFS = new DB_petsSkill.Factory();
	private static readonly DB_enemySkill.Factory _factory2_PFS = new DB_enemySkill.Factory();
	private static readonly DB_petInfo.Factory _factory3_PFS = new DB_petInfo.Factory();
	private static readonly DB_enemyInfo.Factory _factory4_PFS = new DB_enemyInfo.Factory();
	private DB_petsSkill() : base(MetaDefault) {}
	private DB_petsSkill(BGId id) : base(MetaDefault, id) {}
	private DB_petsSkill(BGMetaEntity meta) : base(meta) {}
	private DB_petsSkill(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_petsSkill FindEntity(Predicate<DB_petsSkill> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_petsSkill> FindEntities(Predicate<DB_petsSkill> filter, List<DB_petsSkill> result=null, Comparison<DB_petsSkill> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_petsSkill> action, Predicate<DB_petsSkill> filter=null, Comparison<DB_petsSkill> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_petsSkill GetEntity(BGId entityId) => (DB_petsSkill) MetaDefault.GetEntity(entityId);
	public static DB_petsSkill GetEntity(int index) => (DB_petsSkill) MetaDefault[index];
	public static DB_petsSkill GetEntity(string entityName) => (DB_petsSkill) MetaDefault.GetEntity(entityName);
	public static DB_petsSkill NewEntity() => (DB_petsSkill) MetaDefault.NewEntity();
	public static DB_petsSkill NewEntity(BGId entityId) => (DB_petsSkill) MetaDefault.NewEntity(entityId);
	public static DB_petsSkill NewEntity(Action<DB_petsSkill> callback) => (DB_petsSkill) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_petsSkill)entity)));
}

public partial class DB_enemySkill : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_enemySkill(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_enemySkill(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4638847695599309246UL,2340832625407902112UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String skillName
	{
		get => _skillName[Index];
		set => _skillName[Index] = value;
	}
	public System.Int32 lowDamage
	{
		get => _lowDamage[Index];
		set => _lowDamage[Index] = value;
	}
	public System.Int32 highDamage
	{
		get => _highDamage[Index];
		set => _highDamage[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4885448978335038419UL, 2481677418471852418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillName;
	public static BansheeGz.BGDatabase.BGFieldString _skillName => _ufle12jhs77_skillName ?? (_ufle12jhs77_skillName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350882720540782273UL, 17765573183475609478UL), () => _ufle12jhs77_skillName = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_lowDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _lowDamage => _ufle12jhs77_lowDamage ?? (_ufle12jhs77_lowDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4954465968546606387UL, 5106968816555954598UL), () => _ufle12jhs77_lowDamage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_highDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _highDamage => _ufle12jhs77_highDamage ?? (_ufle12jhs77_highDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4699643514896987962UL, 1250761959635238056UL), () => _ufle12jhs77_highDamage = null));
	private static readonly DB_StageInfo.Factory _factory0_PFS = new DB_StageInfo.Factory();
	private static readonly DB_petsSkill.Factory _factory1_PFS = new DB_petsSkill.Factory();
	private static readonly DB_enemySkill.Factory _factory2_PFS = new DB_enemySkill.Factory();
	private static readonly DB_petInfo.Factory _factory3_PFS = new DB_petInfo.Factory();
	private static readonly DB_enemyInfo.Factory _factory4_PFS = new DB_enemyInfo.Factory();
	private DB_enemySkill() : base(MetaDefault) {}
	private DB_enemySkill(BGId id) : base(MetaDefault, id) {}
	private DB_enemySkill(BGMetaEntity meta) : base(meta) {}
	private DB_enemySkill(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_enemySkill FindEntity(Predicate<DB_enemySkill> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_enemySkill> FindEntities(Predicate<DB_enemySkill> filter, List<DB_enemySkill> result=null, Comparison<DB_enemySkill> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_enemySkill> action, Predicate<DB_enemySkill> filter=null, Comparison<DB_enemySkill> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_enemySkill GetEntity(BGId entityId) => (DB_enemySkill) MetaDefault.GetEntity(entityId);
	public static DB_enemySkill GetEntity(int index) => (DB_enemySkill) MetaDefault[index];
	public static DB_enemySkill GetEntity(string entityName) => (DB_enemySkill) MetaDefault.GetEntity(entityName);
	public static DB_enemySkill NewEntity() => (DB_enemySkill) MetaDefault.NewEntity();
	public static DB_enemySkill NewEntity(BGId entityId) => (DB_enemySkill) MetaDefault.NewEntity(entityId);
	public static DB_enemySkill NewEntity(Action<DB_enemySkill> callback) => (DB_enemySkill) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_enemySkill)entity)));
}

public partial class DB_petInfo : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_petInfo(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_petInfo(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5042940999608266866UL,6266692151645076415UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String animalName
	{
		get => _animalName[Index];
		set => _animalName[Index] = value;
	}
	public System.Int32 hp
	{
		get => _hp[Index];
		set => _hp[Index] = value;
	}
	public System.Int32 mp
	{
		get => _mp[Index];
		set => _mp[Index] = value;
	}
	public UnityEngine.Sprite petFaceImage => _petFaceImage[Index];
	public UnityEngine.Sprite skillOne => _skillOne[Index];
	public UnityEngine.Sprite skillTwo => _skillTwo[Index];
	public UnityEngine.Sprite skillThree => _skillThree[Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5610739267421664898UL, 3996294852943207072UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_animalName;
	public static BansheeGz.BGDatabase.BGFieldString _animalName => _ufle12jhs77_animalName ?? (_ufle12jhs77_animalName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5504866866702260368UL, 5952378322520235151UL), () => _ufle12jhs77_animalName = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5304442055323020872UL, 1360961264623817374UL), () => _ufle12jhs77_hp = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_mp;
	public static BansheeGz.BGDatabase.BGFieldInt _mp => _ufle12jhs77_mp ?? (_ufle12jhs77_mp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5402560827354804245UL, 14758141622572376456UL), () => _ufle12jhs77_mp = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_petFaceImage;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _petFaceImage => _ufle12jhs77_petFaceImage ?? (_ufle12jhs77_petFaceImage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4943749056997808664UL, 1623970025113599912UL), () => _ufle12jhs77_petFaceImage = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_skillOne;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _skillOne => _ufle12jhs77_skillOne ?? (_ufle12jhs77_skillOne = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4810107794027414280UL, 17482864369723719327UL), () => _ufle12jhs77_skillOne = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_skillTwo;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _skillTwo => _ufle12jhs77_skillTwo ?? (_ufle12jhs77_skillTwo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5663328444265580033UL, 9667470489501611444UL), () => _ufle12jhs77_skillTwo = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_skillThree;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _skillThree => _ufle12jhs77_skillThree ?? (_ufle12jhs77_skillThree = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5548289512861789151UL, 9595422688170091156UL), () => _ufle12jhs77_skillThree = null));
	private static readonly DB_StageInfo.Factory _factory0_PFS = new DB_StageInfo.Factory();
	private static readonly DB_petsSkill.Factory _factory1_PFS = new DB_petsSkill.Factory();
	private static readonly DB_enemySkill.Factory _factory2_PFS = new DB_enemySkill.Factory();
	private static readonly DB_petInfo.Factory _factory3_PFS = new DB_petInfo.Factory();
	private static readonly DB_enemyInfo.Factory _factory4_PFS = new DB_enemyInfo.Factory();
	private DB_petInfo() : base(MetaDefault) {}
	private DB_petInfo(BGId id) : base(MetaDefault, id) {}
	private DB_petInfo(BGMetaEntity meta) : base(meta) {}
	private DB_petInfo(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_petInfo FindEntity(Predicate<DB_petInfo> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_petInfo> FindEntities(Predicate<DB_petInfo> filter, List<DB_petInfo> result=null, Comparison<DB_petInfo> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_petInfo> action, Predicate<DB_petInfo> filter=null, Comparison<DB_petInfo> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_petInfo GetEntity(BGId entityId) => (DB_petInfo) MetaDefault.GetEntity(entityId);
	public static DB_petInfo GetEntity(int index) => (DB_petInfo) MetaDefault[index];
	public static DB_petInfo GetEntity(string entityName) => (DB_petInfo) MetaDefault.GetEntity(entityName);
	public static DB_petInfo NewEntity() => (DB_petInfo) MetaDefault.NewEntity();
	public static DB_petInfo NewEntity(BGId entityId) => (DB_petInfo) MetaDefault.NewEntity(entityId);
	public static DB_petInfo NewEntity(Action<DB_petInfo> callback) => (DB_petInfo) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_petInfo)entity)));
}

public partial class DB_enemyInfo : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_enemyInfo(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_enemyInfo(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5337120429478150476UL,10656544974214207381UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String enemyName
	{
		get => _enemyName[Index];
		set => _enemyName[Index] = value;
	}
	public System.Int32 hp
	{
		get => _hp[Index];
		set => _hp[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4620177918891655078UL, 1346771056067299218UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_enemyName;
	public static BansheeGz.BGDatabase.BGFieldString _enemyName => _ufle12jhs77_enemyName ?? (_ufle12jhs77_enemyName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5331987809400633652UL, 6787702961103548827UL), () => _ufle12jhs77_enemyName = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4811283718778953056UL, 17833183804102522298UL), () => _ufle12jhs77_hp = null));
	private static readonly DB_StageInfo.Factory _factory0_PFS = new DB_StageInfo.Factory();
	private static readonly DB_petsSkill.Factory _factory1_PFS = new DB_petsSkill.Factory();
	private static readonly DB_enemySkill.Factory _factory2_PFS = new DB_enemySkill.Factory();
	private static readonly DB_petInfo.Factory _factory3_PFS = new DB_petInfo.Factory();
	private static readonly DB_enemyInfo.Factory _factory4_PFS = new DB_enemyInfo.Factory();
	private DB_enemyInfo() : base(MetaDefault) {}
	private DB_enemyInfo(BGId id) : base(MetaDefault, id) {}
	private DB_enemyInfo(BGMetaEntity meta) : base(meta) {}
	private DB_enemyInfo(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_enemyInfo FindEntity(Predicate<DB_enemyInfo> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_enemyInfo> FindEntities(Predicate<DB_enemyInfo> filter, List<DB_enemyInfo> result=null, Comparison<DB_enemyInfo> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_enemyInfo> action, Predicate<DB_enemyInfo> filter=null, Comparison<DB_enemyInfo> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_enemyInfo GetEntity(BGId entityId) => (DB_enemyInfo) MetaDefault.GetEntity(entityId);
	public static DB_enemyInfo GetEntity(int index) => (DB_enemyInfo) MetaDefault[index];
	public static DB_enemyInfo GetEntity(string entityName) => (DB_enemyInfo) MetaDefault.GetEntity(entityName);
	public static DB_enemyInfo NewEntity() => (DB_enemyInfo) MetaDefault.NewEntity();
	public static DB_enemyInfo NewEntity(BGId entityId) => (DB_enemyInfo) MetaDefault.NewEntity(entityId);
	public static DB_enemyInfo NewEntity(Action<DB_enemyInfo> callback) => (DB_enemyInfo) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_enemyInfo)entity)));
}
#pragma warning restore 414
